/Assets/Samples/XR Hands/1.7.1/HandVisualizer/Models/LeftHand.fbx.meta
/Assets/Samples/XR Hands/1.7.1/HandVisualizer/Models.meta
/Assets/Samples/XR Hands/1.7.1/HandVisualizer/Materials/MaterialPipelineHandler.asset.meta
/Assets/Samples/XR Hands/1.7.1/HandVisualizer/HandVisualizer.unity.meta

/Assets/Samples/XR Hands/1.7.3
/Assets/Samples/XR Hands/1.7.1
/Assets/Samples/XR Hands/1.7.3.meta
/Assets/Samples/XR Hands/1.7.1.meta


*.renderTexture

